FROM denoland/deno:2.5.4

# Install curl (the base image is Debian-based so apt works)
USER root
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# You want hot reload, so we DO NOT copy code here.
# Code will be mounted as a volume.

# Entry script that waits for cloudflared before running Deno
COPY ./entrypoint.dev.sh /usr/local/bin/entrypoint.dev.sh
RUN chmod +x /usr/local/bin/entrypoint.dev.sh

CMD ["entrypoint.dev.sh"]
